### ISSUE TITLE
More problems with the pings

### ISSUE THREAD

**Issue by wragnar** [mgp25/Chat-API#1918]
Make sure these boxes are checked before submitting your issue -- thank you!

- [X ] You are using PHP > 5.6
- [ X] You have installed all extensions and modules listed in [here](https://github.com/mgp25/Chat-API/wiki/Dependencies). PHP Protobuf and Curve25519 are required!
- [ X] You have checked if someone has already asked the same issue you have.
- [ X] You have read the [wiki](https://github.com/mgp25/Chat-API/wiki).
- [ X] Is not a programming question.
- [ X] You are using latest Chat API code.

### Error
I have implement the solution for being blocked, adding a counter for the ping and i make my script like a human use:

ilde, ping ilde ping and wait a random between 2 and 5 second and disconnect, i wait random number of second between 4-6 second and reconnect and start again.

So i can say that the solution
Inactivity
tx ----> send Ping
rx <---- ping response
tx ----> send Ping
rx <---- ping Response

disconect
connect
loginWithPassword

IS NOT WORKING, because after 2 hours executing this flow i have being blocked.

Programing issue? i don't think, because i have being monitoring and the script was acting as a human, with the flow suggested and random timeout .

### Debug log
after 2 hours:

<shutdown></shutdown>
and the script stops 

im not posting the debug, because the script was running in a screen inside a remote view and i can't take the scrolled content back.

Please before closing the issue or blocking the responses, say something that can make the people understand those errors, because last issue i make a comment was closed saying that the solution was on the issue but i have read it a lot of times and in the #1872 is not the answer to the timeout between the pings.

Im writing here to understand why im being blocked, and i write here because i think that people who develop this script can explain me the correct way of using it. When i understand it or if i have information for everyone to prevent those blocking, y will feel free to share with everyone, or i can contribute with other people to help them.

**Comment by eaba** [comment]
I think ping is when you have not heard from the server after, for instance, 60 seconds!
Hope you understand!

**Comment by wragnar** [comment]
I understand the process of pings, i know that its a funtion implemented in whatsprot.class.php that looks for 60 seconds timeout and make automaticaly pings, i put a counter in this function to know when have being made 2 ping and then in my script i look if 2 pings are made to disconnect, wait 4-8 seccons and connect again like its explained in an answer in #1872, but after 2 hour with this script running i get blocked. 

Now i have see that another script that i was runnign on demand in the same machine , (open the script, receive the messages and 10 seconds later close the script, to aboid being blocked) have been blocked too.

I dont know how to look for a solution.

**Comment by feltkamptv** [comment]
I have exactly the same problem. I was blocked too and then implemented a solution (#1913) to count the pings and let the API only send 2 pings, but unfortunately my new number is blocked also. (not spamming, only send message from and to myself) 
I think I am still missing something in the workflow, but I do not know what. I have implemented everything from the wiki and from previous issues and am a bit desperate. 

Here a double check that we are all using the same workflow:

**First login:**
-	connect()
-	loginWithPassword(password)
-	sendGetPrivacyBlockedList() (automatic by API)
-	sendGetClientConfig() (automatic by API)
-	sendGetServerProperties()
-	sendGetGroups()
-	sendGetBroadcastLists()
-	sendSync(array of numbers)
-	sendPresenceSubscription(for each number)
-	sendGetStatuses(array of numbers)
-	sendGetProfilePicture(for each number)
-	pollMessage()

**Other logins:**
-	connect()
-	loginWithPassword(password)
-	sendGetPrivacyBlockedList() (automatic by API)
-	sendGetClientConfig() (automatic by API)
-	pollMessage()

**Only on some logins:**
-	connect()
-	loginWithPassword(password)
-	sendGetPrivacyBlockedList()
-	sendGetClientConfig()
-	sendSync(array of numbers) 
-	pollMessage()

**With every new contact:**
-	sendSync(number)
-	sendPresenceSubscription(number)
-	sendGetProfilePicture(number, true)
-	sendGetStatuses(number)

**Sending a message:** (number needs to be synced first)
-	sendMessageComposing(number)
-	sendMessagePaused(number)
-	sendMessage(number, message)

**After 2 pings send by API:**
-	disconnect()
-	connect()
-	loginWithPassword(password)
-	sendGetPrivacyBlockedList() (automatic by API)
-	sendGetClientConfig() (automatic by API)
-	pollMessage()

**OnProfilePictureChanged:**
- 	sendGetProfilePicture(from, true)

**onNumberWasRemoved:**
-	sendPresenceUnsubscription(jid)
-	sendSync(numbers,delete)

**onNumberWasUpdated:**
-	sendPresenceUnsubscription(jid);
-	sendPresenceSubscription(jid);
-	sendGetProfilePicture(jid); 
-	sendGetStatuses(jid)

@wragnar Did you use the same workflow as mentioned above?

**Comment by wragnar** [comment]
I have being blocked without sending or receiving messages, because that was a number for testing, and i wanted to know if it was a problem with the workflow of the ping or with contacts and messages.

I have being blocked without sending or receiving messages, the script only do the following:
(simplified)


while (true)
{
connect()
loginWithPassword(password)

while $pings <2
     {
     pollMessage()
     }
disconnect
}

2 hours and blocked

**Comment by wragnar** [comment]
Still no solution, no respond but market as duplicate and not related.

How i have to do, to speak about this problem ????

**Comment by feltkamptv** [comment]
Why is it duplicate? Which issue is about that the solution of only sending 2 pings as in #1872, is still giving problems. And why is is not related? This is about this ChatAPI, that with the complete workflow, good coding and normal use, we still get blocked. Seems like a valid issue to me. If not, please tell me why not.

**Comment by luciano-work** [comment]
@feltkamptv and @wragnar 

They do not have the answer to this problem I think. 
I gave up using the API !

**Comment by lssca** [comment]
There is no code problems , blockage occurs in the way that the channel was created.

**Comment by KduOliva** [comment]
same here, i try all this "solutions" and always get blocked. Some times after a couple os minutes, some times couple of months.

**Comment by Sdlion** [comment]
It should be better if with the tag of duplicated would come a comment with the original issue to comment in just one thread.

Yesterday I implemented the 2-ping-and-reconnect and worked for lots of hours until I got blocked.
It seems Whatsapp was more lenient on all the "Don'ts and Musts" that are all over the documentation, and now is quite stricter. I got a few numbers permanently blocked because I was breaking rules about subscribing/unsubscribing/syncing, so you may want to re-read your logic and the rules (and logs) to understand what rule are you breaking.

Reading the logs (when I got banned after a few hours) I noted that there was no message send when I got blocked, it was just that for some reason my counter in `whatsprot.class.php` was hitting the 2-ping limit early. One ping and the next time it would reconnect and login (without reason... that I could understand). Since I didn't modify the default 1 min lapse for each ping, my client got logging in very frequently (each 2 minutes) and I guess that was the reason I got banned. I ended up erasing the `sendPing()` all-together from the `pollMessage()` method and implement all the code in my script class.

Today I raised my ping lapse up to 5 min, but I count from the last activity I have shown to the server. So if the counter is on the 4 minute mark and I send a message, I reset it. If I sync some contact, I reset it... subscribe, unsubscribe, etcétera. All activity that would show a `tx` mark on the debug mode, will reset my activity time keep variable. That way the ping only is send on inactivity, and it may be not be sent at all if there's activity from my cellphone with my script.

So, don't ... do anything too often and don't break the rules.

I wrote some more in https://github.com/mgp25/Chat-API/issues/1899#issuecomment-222841268



Reading the logs and the timestamps (`t='unix-time'` attribute in some `rx` lines)

**Comment by KduOliva** [comment]
Hi guys, any solution? I read almost avery issue openned, coded with all sugestions gived, include the 2-ping-reconnect and still get blocked in a few hous
